apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true     
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 81.0.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/helm-values/kube-prometheus-stack/values.yaml

    - repoURL: https://github.com/prometheus-community/helm-charts.git
      targetRevision: 81.0.0
      paths: 
        - charts/kube-prometheus-stack/charts/crds/crds

    - repoURL: https://github.com/prinnnnnn/capstone-gitops.git
      targetRevision: main
      ref: values
    
    - repoURL: https://github.com/prinnnnnn/capstone-gitops.git
      targetRevision: main
      paths: 
        - infrastructure/monitoring/config-map.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring 
