apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-users
  namespace: monitoring
data:
  users.yaml: |
    apiVersion: 1
    users:
      - name: readonly
        password: ReadOnlyPassword123
        role: Viewer